version: 2
updates:
  - package-ecosystem: mix
    directory: /
    schedule:
      interval: weekly
    groups:
      hex-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /assets
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
