defmodule NewtonWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :newton

  # The session cookie is signed (tamper-proof) and encrypted (opaque to the
  # client). Salts derive keys from SECRET_KEY_BASE; they are not secrets.
  @session_options [
    store: :cookie,
    key: "_newton_key",
    signing_salt: "SQAKAS3y",
    encryption_salt: "Sn35u8INx76v",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # User images (not fingerprinted assets) served from a configurable root.
  # This plug halts before the router, so the :browser pipeline's CSP never
  # reaches these responses — they carry their own. `default-src 'none'` plus
  # `sandbox` means even a file that somehow lands here with an executable
  # content type renders inert and same-origin-less.
  plug Plug.Static,
    at: "/media",
    from: Application.compile_env(:newton, :media_root),
    gzip: false,
    headers: %{
      "x-content-type-options" => "nosniff",
      "content-security-policy" => "default-src 'none'; img-src 'self'; sandbox",
      "x-frame-options" => "DENY"
    }

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :newton,
    gzip: not code_reloading?,
    only: NewtonWeb.static_paths(),
    # Digested top-level files (e.g. favicon-HASH.png, og-default-HASH.png) don't
    # match the exact `:only` names, so allow them by prefix. Without this they
    # 404 in production once phx.digest rewrites the URLs.
    only_matching: ~w(favicon apple-touch-icon og-default robots),
    raise_on_missing_only: code_reloading?

  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :newton
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug NewtonWeb.Router
end
