import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :newton, NewtonWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :newton, NewtonWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    # include_subdomains stops an attacker who can answer DNS for a name we
    # never created (evil.jamesnewton.com) from serving plain HTTP there and
    # setting a .jamesnewton.com cookie the apex would then receive. Deliberately
    # no `preload`: that ships the domain inside browser binaries and takes
    # months to undo.
    expires: 31_536_000,
    subdomains: true,
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

config :newton, :media_root, "/data/images"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Kept off while jamesnewton-com.fly.dev serves as staging — no reason to ping
# search engines about the staging host. Flip to true once jamesnewton.com goes live.
config :newton, Newton.IndexNow, enabled: false

config :newton, Newton.PromEx, metrics_server: [port: 9091]
